In [2]:
import torch
torch.__version__

'2.1.2+cu118'

In [3]:
# Scalar, a zero dimension tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Check the dimensions of a tensor
scalar.ndim

0

In [5]:
# Get the number form within the tensor (Only works with one element tensor)
scalar.item()

7

In [6]:
# Vector, a single dimension tensor.
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# Get the shape of the elements inside a tensor.
vector.shape

torch.Size([2])

In [8]:
# Matrix, two dimensional tensor
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
# MATRIX is two elements deep and two elements wide
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor, multidimensional tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# TENSOR's shape is 1 dimension with a 3 by 3 grid
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
# Creating a tensor of random numbers, essential for machine learning.
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1904, 0.3280, 0.5118, 0.4368],
         [0.1075, 0.1648, 0.0282, 0.2085],
         [0.5921, 0.0100, 0.5955, 0.8074]]),
 torch.float32)

In [14]:
# Creating tensors full of zeroes and ones, to be used for masking
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [15]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [16]:
# Creating tensors of a range of numbers with torch.arange(start, end, step)
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Making zeros and ones tensors with the same shape as another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

There are many different types of tensors available in PyTorch, some specific for the CPU and some for the GPU.

If torch.cuda is used anywhere in the code you're examining, then this tensor is being used for the GPU, named afyer NVidia's toolkit CUDA.

The most common type (and generally the default) is torch.float32 or torch.float

This is referred to as "32-bit floating point"

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double)

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers

Plus more!

-------------------------------------------------------------------------------

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more computer you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

In [18]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [19]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16)

float_16_tensor.dtype

torch.float16

## Getting information from tensors

In [20]:
# Three most common attributes you want to get are:
# shape
# dtype - for data type
# device - CPU or GPU
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.0339, 0.5925, 0.7413, 0.3090],
        [0.2849, 0.5561, 0.6370, 0.5168],
        [0.3307, 0.5713, 0.0558, 0.4288]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors

In [21]:
# Basic operations, addition, subtraction and multiplication
# They work just like any mathematical operation in python
tensor = torch.tensor([1,2, 3])
tensor + 10


tensor([11, 12, 13])

In [22]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [23]:
# Tensors don't change unless they're reassigned
tensor

tensor([1, 2, 3])

In [24]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [25]:
# Matrix multipilication, the basic building block
# The inner dimensions of the matrices must be equal
# And the produced matrix has the shape of the outer dimensions

tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [26]:
# Element wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [27]:
# Matrix multiplication, elements multiplied then added
tensor.matmul(tensor)

tensor(14)

In [28]:
# Matrix multiplication with incompatible shapes:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

print(f"We'll try to multiply tensors A and B of shapes{tensor_A.shape} and {tensor_B.shape}.")
tensor_A.matmul(tensor_B)

We'll try to multiply tensors A and B of shapestorch.Size([3, 2]) and torch.Size([3, 2]).


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# The inner dimensions do not match in the previous cell.
# We can transpose matrix B and switch its dimensions to work this out.
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")

print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [ ]:
# torch.mm == torch.matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Feed forward layer, applies a linear function on input.

torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features = 6) # out_features = describes outer value

x = tensor_A
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min, max, mean, sum etc..
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Meamn: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Meamn: 45.0
Sum: 450


In [ ]:
# Find the position index of the min/max
print(x)
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 9
Index where min value occurs: 0


In [29]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [33]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [34]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [35]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## PyTorch tensors & NumPy

In [37]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Numpy arrays are created with datatype float64 by default, and that datatype is maintained when converting it to a tensor. Since many PyTorch calculations default to using float32, you'll have to convert the datatype after converting.

In [47]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Randomizing with seed, for reproducibility

In [48]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Checking for Nvidia GPU and using it for tensor operations

In [39]:
!nvidia-smi

Tue Feb  6 09:01:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.34                 Driver Version: 537.34       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   31C    P0              23W /  80W |      0MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [40]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [41]:
# Set device type so it can use wither the CPU ot the GPU depending on what
# is available
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [42]:
# Creating a tensor and explicitly putting it in a device using "to"
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

## Exercises

In [44]:
# Create a random tensor with shape (7, 7)
tensor = torch.rand(7, 7)
tensor

tensor([[0.2473, 0.7411, 0.3644, 0.6264, 0.5589, 0.7853, 0.7597],
        [0.1785, 0.5754, 0.7462, 0.4227, 0.1491, 0.0674, 0.0102],
        [0.4245, 0.3725, 0.8534, 0.9814, 0.1143, 0.4122, 0.8241],
        [0.5170, 0.6542, 0.4977, 0.9343, 0.6949, 0.9209, 0.0398],
        [0.1738, 0.3727, 0.4522, 0.6564, 0.3099, 0.9736, 0.2343],
        [0.2662, 0.6812, 0.8973, 0.6769, 0.1665, 0.9116, 0.9888],
        [0.1805, 0.4534, 0.8836, 0.4504, 0.4591, 0.4321, 0.8642]])

In [46]:
# Perform a matrix multiplication on the tensor from 2 with another random 
# tensor with shape (1, 7)
tensor2 = torch.rand(1, 7)
torch.mm(tensor, tensor2.T)


tensor([[1.9270],
        [1.1867],
        [1.9540],
        [2.0953],
        [1.5650],
        [2.2410],
        [1.9934]])

In [50]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
SEED = 0
torch.manual_seed(seed=SEED)
rand_tensor1 = torch.rand(7, 7)

torch.random.manual_seed(seed=SEED)
rand_tensor2 = torch.rand(1, 7).T

torch.mm(rand_tensor1, rand_tensor2)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [52]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() 
# but is there a GPU equivalent? Set the GPU random seed to 1234
torch.cuda.manual_seed(1234)

In [56]:
# Create two random tensors of shape (2, 3) and send them both to the GPU 
# Set torch.manual_seed(1234) when creating the tensors
torch.manual_seed(1234)
gpu_tensor1 = torch.rand(2, 3).to("cuda")
torch.manual_seed(1234)
gpu_tensor2 = torch.rand(2, 3).to("cuda")

gpu_tensor1, gpu_tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [58]:
# Perform a matrix multiplication on the tensors you created in 6 
# (again, you may have to adjust the shapes of one of the tensors).
mult_tensor = torch.mm(gpu_tensor1, gpu_tensor2.T)


In [66]:
# Find the maximum and minimum values of the output of 7.
print("Maximum value: {}".format(mult_tensor.max()))
print("Minimum value: {}".format(mult_tensor.min()))


Maximum value: 0.628727912902832
Minimum value: 0.21611443161964417


In [67]:
# Find the maximum and minimum index values of the output of 7.
print("Maximum value index: {}".format(mult_tensor.argmax()))
print("Minimum value index: {}".format(mult_tensor.argmin()))

Maximum value index: 3
Minimum value index: 1


In [69]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor 
# with all the 1 dimensions removed to be left with a tensor of shape (10). 
# Set the seed to 7 when you create it and print out the first tensor and it's 
# shape as well as the second tensor and it's shape.

SEED = 7
torch.manual_seed(SEED)
tensor1 = torch.rand(1, 1, 1, 10)
print("The first tensor: {}".format(tensor1))
print("Its shape: {}".format(tensor1.shape))

# We can use the view function to resize our tensor
torch.manual_seed(SEED)
tensor2 = tensor1.view(10)
print("The second tensor: {}".format(tensor2))
print("Its shape: {}".format(tensor2.shape))


The first tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Its shape: torch.Size([1, 1, 1, 10])
The second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Its shape: torch.Size([10])
